### ISSUE TITLE
Preedit while typing should be in English so that corrections can be easily made

### ISSUE THREAD

**Issue by subins2000** [varnamproject/varnam-fcitx5#10]
In the below example, while typing the preedit text it should come up as it is. This helps to easily make corrections to the preedit when a mistake is made.

![2024-07-28_13-38](https://github.com/user-attachments/assets/c56f1419-db3a-4a76-9f65-8e576866cacb)

**Comment by anoopmsivadas** [comment]
@subins2000 this was fixed on #8 I believe. Can you uninstall and reinstall it once?

![Screenshot from 2024-07-28 22-29-05](https://github.com/user-attachments/assets/18793cda-7864-4df6-b0ee-bd20220bf4f1)

**Comment by subins2000** [comment]
Yes it's working. For some reason my old fcitx5 version was being used, and removing it was difficult. Sorry
